title: Facilitation Fest NYC
description: > # this means to ignore newlines until "baseurl:"
  In the spirit of international exchange and with the support of the Taiwanese
  government, we are pleased to announce the first English language opportunity
  to learn the facilitation methods that power the award-winning vTaiwan open
  consultation process.
baseurl: "" # the subpath of your site, e.g. /blog
url: nyc.g0v.network # the base hostname & protocol for your site
# Build settings
markdown: kramdown

speaker_term: Facilitators

facebook:
  app_id: null

logo: "../css/2016_style/img/icon-large.png"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/TalktoNYC

# Build settings
markdown: kramdown
permalink: pretty
